name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: | 
       sudo docker build -t baksey .
       sudo docker tag baksey krishnoit/baksey
       sudo docker push krishnoit/baksey
      
